### ISSUE TITLE
About replay buffer 

### ISSUE THREAD

**Issue by zanghyu** [bbrighttaer/irelease#1]
Hi,
I have some questions about the replay buffer.  I found that in [Link](https://github.com/bbrighttaer/irelease/blob/master/irelease/rl.py#L524), we sample the trajectories from the replay buffer and then concate the experiment trajectories and the sampled trajectories, and finally push the concated trajectories back to the replay buffer. However, based on the code, once the size of the replay buffer is not larger than its batch_size, it will sample all trajectories in the replay buffer and do the following steps, then the trajectories will be added repetitively, i.e., in the first iteration of the ``fit`` function, len(trajectories) will be 12+0=12, the size of the replay buffer will be 0+12 = 12; in the second iteration, len(trajectories) will be 12+12=24, the size of the replay buffer will be 12+24 = 36. Then the trajectories of the experiment trajectories from the first iteration will be duplicated. Right? It seems a little bit weird for me.

**Comment by zanghyu** [comment]
Besides, since we reset the trajectories list every time after one fit step has done in [Link](https://github.com/bbrighttaer/irelease/blob/master/proj/ppo_rl_drd2.py#L370), ``trajectories`` passes into the ``fit`` function will always be the length of 12. And since the batch_size of the replay buffer is about 100, d_samp_out.shape[0] will never greater than 1000, therefore the condition [link](https://github.com/bbrighttaer/irelease/blob/master/irelease/rl.py#L547) will always be true. There are some of my concerns, thanks.

**Comment by bbrighttaer** [comment]
Hi @zanghyu,
Thank you for linking up. 
I have taken a few minutes to understand the issues you've pointed out. My thought is that [Line 523 of rl.py](https://github.com/bbrighttaer/irelease/blob/15839ef0219ed155d71b9c613bc898e34688955c/irelease/rl.py#L523) should rather be:
```python
if self.use_buffer:
        # first sample from the buffer
        extra_trajs = self.replay_buffer.sample(self.batch_size)
        # add the current trajectories to the buffer
        self.replay_buffer.populate(trajectories)
        # add the entries sampled from the buffer to the current trajectories
        trajectories.extend(extra_trajs)
```
In the above code, calling `self.replay_buffer.populate(trajectories)` invokes a [loop ](https://github.com/bbrighttaer/irelease/blob/15839ef0219ed155d71b9c613bc898e34688955c/irelease/rl.py#L598) where the entries in `trajectories` are added to the [buffer](https://github.com/bbrighttaer/irelease/blob/15839ef0219ed155d71b9c613bc898e34688955c/irelease/rl.py#L573). Thus, calling `trajectories.clear()` [here](https://github.com/bbrighttaer/irelease/blob/15839ef0219ed155d71b9c613bc898e34688955c/proj/ppo_rl_drd2.py#L370) does not clear the buffer (if I understand your point).
Perhaps this illustration may help my point:
```bash
>>> trajectories = [['a','b','c'], ['d','e','f']] 
>>> trajectories
[['a', 'b', 'c'], ['d', 'e', 'f']]
>>> buffer = [t for t in trajectories]
>>> buffer 
[['a', 'b', 'c'], ['d', 'e', 'f']]
>>> trajectories.clear()
>>> trajectories
[]
>>> buffer
[['a', 'b', 'c'], ['d', 'e', 'f']]
```

That said, one possible improvement could be to constrain the buffer to keep only unique SMILES. Thanks also for pointing out the mistake of adding the trajectories to the buffer.

**Comment by zanghyu** [comment]
Yes, that is my point.  And my second question is:  will the condition in [here](https://github.com/bbrighttaer/irelease/blob/master/irelease/rl.py#L546) always be true?

**Comment by bbrighttaer** [comment]
Since the buffer can grow to its capacity, [it](https://github.com/bbrighttaer/irelease/blob/632e204436027fe30c2a3a22a1040fc0cd996a94/irelease/rl.py#L549) would not always be true if the buffer size is set to 1000. Note that 1000 used here is arbitrary and could be any value as desired. The rationale is to control when mixing the demonstrations with the samples from the generator for IRL training should be allowed.
I hope this helps.
Thanks!

**Comment by zanghyu** [comment]
Hi, @bbrighttaer,
As you mentioned, [Line 523 of rl.py](https://github.com/bbrighttaer/irelease/blob/master/irelease/rl.py#L523) should rather be:

```
if self.use_buffer:
    self.replay_buffer.populate(trajectories)
    extra_trajs = self.replay_buffer.sample(self.batch_size)
    trajectories.extend(extra_trajs)
```

In the above code, we sample trajectories from buffer with the length of `batch_size`, and contact them to `trajectories`.  Then whatever the buffer size is, the maximum size of trajectories will be `self.batch_size` plus the size of `trajectories` pass into the `fit` function. Example:

```
>>> trajectories = [1,1,1]
>>> buffer = np.array([i for i in range(1000)])
>>> batch_size = 5
>>> result = np.random.choice(buffer, batch_size)
>>> result
array([346, 700, 407, 884, 119])
>>> trajectories.extend(result)
[1,1,1,346, 700, 407, 884, 119]
```

Since the batch_size is fitted, the maximum size is constant. For instance, in the code, since `episodes_to_train=12, buffer_batch_size=100`, the maximum value of `d_samp_out.shape[0]` will be 100+12=112.

**Comment by bbrighttaer** [comment]
Yeah, as I mentioned, the number of trajectories can vary and the same applies to the value in the condition. At a point, I experimented with adding the demos to the trajs always hence the `1000` (it was `100` initially). You may set it at a different value that would ensure that it is not true always (and control the number of trajectories).

**Comment by zanghyu** [comment]
I see what you mean, thanks.
